# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/prosopite/all/prosopite.rbi
#
# prosopite-1.0.9

module Prosopite
  def self.allow_list=(value); end
  def self.allow_stack_paths=(arg0); end
  def self.create_notifications; end
  def self.custom_logger=(arg0); end
  def self.fingerprint(query); end
  def self.finish; end
  def self.ignore_queries=(arg0); end
  def self.ignore_query?(sql); end
  def self.mysql_fingerprint(query); end
  def self.pause; end
  def self.prosopite_logger=(arg0); end
  def self.rails_logger=(arg0); end
  def self.raise=(arg0); end
  def self.red(str); end
  def self.resume; end
  def self.scan; end
  def self.scan?; end
  def self.send_notifications; end
  def self.stderr_logger=(arg0); end
  def self.subscribe; end
  def self.tc; end
end
class Prosopite::NPlusOneQueriesError < StandardError
end
