# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/tzinfo-data/all/tzinfo-data.rbi
#
# tzinfo-data-1.2022.1

module TZInfo
end
module TZInfo::Data
end
module TZInfo::Data::Version
end
module TZInfo::Data::Definitions
end
module TZInfo::Data::Definitions::Etc
end
module TZInfo::Data::Definitions::Etc::UTC
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Indexes
end
module TZInfo::Data::Indexes::Timezones
  extend TZInfo::TimezoneIndexDefinition::ClassMethods
  include TZInfo::TimezoneIndexDefinition
end
module TZInfo::Data::Definitions::Africa
end
module TZInfo::Data::Definitions::Africa::Abidjan
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Africa::Accra
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Africa::Addis_Ababa
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Africa::Nairobi
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Africa::Algiers
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Africa::Asmara
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Africa::Asmera
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Africa::Bamako
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Africa::Bangui
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Africa::Lagos
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Africa::Banjul
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Africa::Bissau
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Africa::Blantyre
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Africa::Maputo
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Africa::Brazzaville
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Africa::Bujumbura
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Africa::Cairo
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Africa::Casablanca
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Africa::Ceuta
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Africa::Conakry
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Africa::Dakar
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Africa::Dar_es_Salaam
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Africa::Djibouti
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Africa::Douala
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Africa::El_Aaiun
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Africa::Freetown
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Africa::Gaborone
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Africa::Harare
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Africa::Johannesburg
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Africa::Juba
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Africa::Kampala
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Africa::Khartoum
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Africa::Kigali
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Africa::Kinshasa
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Africa::Libreville
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Africa::Lome
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Africa::Luanda
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Africa::Lubumbashi
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Africa::Lusaka
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Africa::Malabo
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Africa::Maseru
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Africa::Mbabane
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Africa::Mogadishu
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Africa::Monrovia
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Africa::Ndjamena
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Africa::Niamey
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Africa::Nouakchott
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Africa::Ouagadougou
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Africa::Porto__m__Novo
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Africa::Sao_Tome
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Africa::Timbuktu
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Africa::Tripoli
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Africa::Tunis
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Africa::Windhoek
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::America
end
module TZInfo::Data::Definitions::America::Adak
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::America::Anchorage
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::America::Anguilla
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::America::Puerto_Rico
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::America::Antigua
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::America::Araguaina
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::America::Argentina
end
module TZInfo::Data::Definitions::America::Argentina::Buenos_Aires
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::America::Argentina::Catamarca
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::America::Argentina::ComodRivadavia
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::America::Argentina::Cordoba
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::America::Argentina::Jujuy
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::America::Argentina::La_Rioja
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::America::Argentina::Mendoza
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::America::Argentina::Rio_Gallegos
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::America::Argentina::Salta
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::America::Argentina::San_Juan
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::America::Argentina::San_Luis
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::America::Argentina::Tucuman
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::America::Argentina::Ushuaia
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::America::Aruba
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::America::Asuncion
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::America::Atikokan
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::America::Panama
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::America::Atka
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::America::Bahia
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::America::Bahia_Banderas
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::America::Barbados
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::America::Belem
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::America::Belize
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::America::Blanc__m__Sablon
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::America::Boa_Vista
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::America::Bogota
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::America::Boise
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::America::Buenos_Aires
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::America::Cambridge_Bay
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::America::Campo_Grande
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::America::Cancun
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::America::Caracas
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::America::Catamarca
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::America::Cayenne
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::America::Cayman
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::America::Chicago
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::America::Chihuahua
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::America::Coral_Harbour
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::America::Cordoba
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::America::Costa_Rica
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::America::Creston
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::America::Phoenix
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::America::Cuiaba
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::America::Curacao
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::America::Danmarkshavn
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::America::Dawson
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::America::Dawson_Creek
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::America::Denver
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::America::Detroit
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::America::Dominica
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::America::Edmonton
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::America::Eirunepe
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::America::El_Salvador
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::America::Ensenada
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::America::Tijuana
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::America::Fort_Nelson
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::America::Fort_Wayne
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::America::Indiana
end
module TZInfo::Data::Definitions::America::Indiana::Indianapolis
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::America::Fortaleza
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::America::Glace_Bay
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::America::Godthab
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::America::Nuuk
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::America::Goose_Bay
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::America::Grand_Turk
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::America::Grenada
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::America::Guadeloupe
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::America::Guatemala
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::America::Guayaquil
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::America::Guyana
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::America::Halifax
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::America::Havana
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::America::Hermosillo
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::America::Indiana::Knox
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::America::Indiana::Marengo
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::America::Indiana::Petersburg
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::America::Indiana::Tell_City
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::America::Indiana::Vevay
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::America::Indiana::Vincennes
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::America::Indiana::Winamac
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::America::Indianapolis
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::America::Inuvik
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::America::Iqaluit
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::America::Jamaica
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::America::Jujuy
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::America::Juneau
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::America::Kentucky
end
module TZInfo::Data::Definitions::America::Kentucky::Louisville
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::America::Kentucky::Monticello
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::America::Knox_IN
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::America::Kralendijk
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::America::La_Paz
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::America::Lima
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::America::Los_Angeles
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::America::Louisville
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::America::Lower_Princes
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::America::Maceio
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::America::Managua
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::America::Manaus
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::America::Marigot
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::America::Martinique
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::America::Matamoros
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::America::Mazatlan
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::America::Mendoza
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::America::Menominee
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::America::Merida
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::America::Metlakatla
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::America::Mexico_City
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::America::Miquelon
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::America::Moncton
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::America::Monterrey
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::America::Montevideo
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::America::Montreal
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::America::Toronto
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::America::Montserrat
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::America::Nassau
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::America::New_York
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::America::Nipigon
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::America::Nome
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::America::Noronha
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::America::North_Dakota
end
module TZInfo::Data::Definitions::America::North_Dakota::Beulah
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::America::North_Dakota::Center
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::America::North_Dakota::New_Salem
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::America::Ojinaga
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::America::Pangnirtung
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::America::Paramaribo
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::America::Port__m__au__m__Prince
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::America::Port_of_Spain
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::America::Porto_Acre
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::America::Rio_Branco
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::America::Porto_Velho
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::America::Punta_Arenas
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::America::Rainy_River
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::America::Rankin_Inlet
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::America::Recife
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::America::Regina
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::America::Resolute
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::America::Rosario
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::America::Santa_Isabel
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::America::Santarem
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::America::Santiago
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::America::Santo_Domingo
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::America::Sao_Paulo
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::America::Scoresbysund
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::America::Shiprock
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::America::Sitka
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::America::St_Barthelemy
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::America::St_Johns
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::America::St_Kitts
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::America::St_Lucia
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::America::St_Thomas
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::America::St_Vincent
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::America::Swift_Current
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::America::Tegucigalpa
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::America::Thule
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::America::Thunder_Bay
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::America::Tortola
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::America::Vancouver
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::America::Virgin
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::America::Whitehorse
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::America::Winnipeg
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::America::Yakutat
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::America::Yellowknife
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Antarctica
end
module TZInfo::Data::Definitions::Antarctica::Casey
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Antarctica::Davis
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Antarctica::DumontDUrville
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Pacific
end
module TZInfo::Data::Definitions::Pacific::Port_Moresby
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Antarctica::Macquarie
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Antarctica::Mawson
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Antarctica::McMurdo
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Pacific::Auckland
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Antarctica::Palmer
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Antarctica::Rothera
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Antarctica::South_Pole
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Antarctica::Syowa
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Asia
end
module TZInfo::Data::Definitions::Asia::Riyadh
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Antarctica::Troll
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Antarctica::Vostok
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Arctic
end
module TZInfo::Data::Definitions::Arctic::Longyearbyen
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Europe
end
module TZInfo::Data::Definitions::Europe::Oslo
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Asia::Aden
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Asia::Almaty
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Asia::Amman
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Asia::Anadyr
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Asia::Aqtau
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Asia::Aqtobe
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Asia::Ashgabat
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Asia::Ashkhabad
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Asia::Atyrau
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Asia::Baghdad
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Asia::Bahrain
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Asia::Qatar
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Asia::Baku
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Asia::Bangkok
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Asia::Barnaul
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Asia::Beirut
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Asia::Bishkek
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Asia::Brunei
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Asia::Calcutta
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Asia::Kolkata
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Asia::Chita
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Asia::Choibalsan
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Asia::Chongqing
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Asia::Shanghai
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Asia::Chungking
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Asia::Colombo
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Asia::Dacca
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Asia::Dhaka
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Asia::Damascus
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Asia::Dili
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Asia::Dubai
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Asia::Dushanbe
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Asia::Famagusta
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Asia::Gaza
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Asia::Harbin
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Asia::Hebron
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Asia::Ho_Chi_Minh
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Asia::Hong_Kong
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Asia::Hovd
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Asia::Irkutsk
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Asia::Istanbul
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Europe::Istanbul
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Asia::Jakarta
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Asia::Jayapura
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Asia::Jerusalem
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Asia::Kabul
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Asia::Kamchatka
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Asia::Karachi
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Asia::Kashgar
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Asia::Urumqi
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Asia::Kathmandu
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Asia::Katmandu
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Asia::Khandyga
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Asia::Krasnoyarsk
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Asia::Kuala_Lumpur
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Asia::Kuching
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Asia::Kuwait
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Asia::Macao
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Asia::Macau
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Asia::Magadan
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Asia::Makassar
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Asia::Manila
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Asia::Muscat
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Asia::Nicosia
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Asia::Novokuznetsk
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Asia::Novosibirsk
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Asia::Omsk
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Asia::Oral
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Asia::Phnom_Penh
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Asia::Pontianak
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Asia::Pyongyang
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Asia::Qostanay
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Asia::Qyzylorda
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Asia::Rangoon
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Asia::Yangon
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Asia::Saigon
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Asia::Sakhalin
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Asia::Samarkand
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Asia::Seoul
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Asia::Singapore
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Asia::Srednekolymsk
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Asia::Taipei
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Asia::Tashkent
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Asia::Tbilisi
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Asia::Tehran
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Asia::Tel_Aviv
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Asia::Thimbu
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Asia::Thimphu
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Asia::Tokyo
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Asia::Tomsk
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Asia::Ujung_Pandang
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Asia::Ulaanbaatar
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Asia::Ulan_Bator
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Asia::Ust__m__Nera
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Asia::Vientiane
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Asia::Vladivostok
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Asia::Yakutsk
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Asia::Yekaterinburg
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Asia::Yerevan
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Atlantic
end
module TZInfo::Data::Definitions::Atlantic::Azores
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Atlantic::Bermuda
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Atlantic::Canary
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Atlantic::Cape_Verde
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Atlantic::Faeroe
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Atlantic::Faroe
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Atlantic::Jan_Mayen
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Atlantic::Madeira
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Atlantic::Reykjavik
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Atlantic::South_Georgia
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Atlantic::St_Helena
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Atlantic::Stanley
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Australia
end
module TZInfo::Data::Definitions::Australia::ACT
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Australia::Sydney
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Australia::Adelaide
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Australia::Brisbane
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Australia::Broken_Hill
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Australia::Canberra
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Australia::Currie
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Australia::Hobart
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Australia::Darwin
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Australia::Eucla
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Australia::LHI
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Australia::Lord_Howe
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Australia::Lindeman
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Australia::Melbourne
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Australia::NSW
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Australia::North
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Australia::Perth
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Australia::Queensland
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Australia::South
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Australia::Tasmania
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Australia::Victoria
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Australia::West
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Australia::Yancowinna
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Brazil
end
module TZInfo::Data::Definitions::Brazil::Acre
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Brazil::DeNoronha
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Brazil::East
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Brazil::West
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::CET
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::CST6CDT
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Canada
end
module TZInfo::Data::Definitions::Canada::Atlantic
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Canada::Central
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Canada::Eastern
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Canada::Mountain
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Canada::Newfoundland
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Canada::Pacific
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Canada::Saskatchewan
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Canada::Yukon
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Chile
end
module TZInfo::Data::Definitions::Chile::Continental
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Chile::EasterIsland
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Pacific::Easter
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Cuba
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::EET
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::EST
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::EST5EDT
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Egypt
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Eire
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Europe::Dublin
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Etc::GMT
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Etc::GMT__p__0
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Etc::GMT__p__1
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Etc::GMT__p__10
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Etc::GMT__p__11
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Etc::GMT__p__12
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Etc::GMT__p__2
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Etc::GMT__p__3
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Etc::GMT__p__4
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Etc::GMT__p__5
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Etc::GMT__p__6
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Etc::GMT__p__7
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Etc::GMT__p__8
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Etc::GMT__p__9
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Etc::GMT__m__0
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Etc::GMT__m__1
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Etc::GMT__m__10
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Etc::GMT__m__11
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Etc::GMT__m__12
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Etc::GMT__m__13
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Etc::GMT__m__14
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Etc::GMT__m__2
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Etc::GMT__m__3
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Etc::GMT__m__4
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Etc::GMT__m__5
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Etc::GMT__m__6
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Etc::GMT__m__7
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Etc::GMT__m__8
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Etc::GMT__m__9
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Etc::GMT0
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Etc::Greenwich
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Etc::UCT
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Etc::Universal
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Etc::Zulu
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Europe::Amsterdam
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Europe::Andorra
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Europe::Astrakhan
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Europe::Athens
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Europe::Belfast
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Europe::London
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Europe::Belgrade
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Europe::Berlin
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Europe::Bratislava
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Europe::Prague
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Europe::Brussels
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Europe::Bucharest
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Europe::Budapest
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Europe::Busingen
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Europe::Zurich
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Europe::Chisinau
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Europe::Copenhagen
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Europe::Gibraltar
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Europe::Guernsey
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Europe::Helsinki
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Europe::Isle_of_Man
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Europe::Jersey
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Europe::Kaliningrad
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Europe::Kiev
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Europe::Kirov
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Europe::Lisbon
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Europe::Ljubljana
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Europe::Luxembourg
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Europe::Madrid
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Europe::Malta
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Europe::Mariehamn
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Europe::Minsk
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Europe::Monaco
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Europe::Moscow
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Europe::Nicosia
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Europe::Paris
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Europe::Podgorica
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Europe::Riga
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Europe::Rome
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Europe::Samara
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Europe::San_Marino
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Europe::Sarajevo
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Europe::Saratov
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Europe::Simferopol
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Europe::Skopje
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Europe::Sofia
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Europe::Stockholm
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Europe::Tallinn
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Europe::Tirane
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Europe::Tiraspol
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Europe::Ulyanovsk
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Europe::Uzhgorod
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Europe::Vaduz
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Europe::Vatican
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Europe::Vienna
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Europe::Vilnius
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Europe::Volgograd
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Europe::Warsaw
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Europe::Zagreb
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Europe::Zaporozhye
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Factory
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::GB
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::GB__m__Eire
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::GMT
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::GMT__p__0
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::GMT__m__0
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::GMT0
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Greenwich
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::HST
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Hongkong
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Iceland
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Indian
end
module TZInfo::Data::Definitions::Indian::Antananarivo
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Indian::Chagos
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Indian::Christmas
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Indian::Cocos
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Indian::Comoro
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Indian::Kerguelen
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Indian::Mahe
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Indian::Maldives
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Indian::Mauritius
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Indian::Mayotte
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Indian::Reunion
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Iran
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Israel
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Jamaica
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Japan
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Kwajalein
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Pacific::Kwajalein
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Libya
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::MET
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::MST
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::MST7MDT
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Mexico
end
module TZInfo::Data::Definitions::Mexico::BajaNorte
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Mexico::BajaSur
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Mexico::General
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::NZ
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::NZ__m__CHAT
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Pacific::Chatham
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Navajo
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::PRC
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::PST8PDT
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Pacific::Apia
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Pacific::Bougainville
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Pacific::Chuuk
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Pacific::Efate
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Pacific::Enderbury
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Pacific::Kanton
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Pacific::Fakaofo
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Pacific::Fiji
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Pacific::Funafuti
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Pacific::Galapagos
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Pacific::Gambier
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Pacific::Guadalcanal
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Pacific::Guam
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Pacific::Honolulu
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Pacific::Johnston
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Pacific::Kiritimati
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Pacific::Kosrae
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Pacific::Majuro
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Pacific::Marquesas
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Pacific::Midway
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Pacific::Pago_Pago
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Pacific::Nauru
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Pacific::Niue
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Pacific::Norfolk
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Pacific::Noumea
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Pacific::Palau
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Pacific::Pitcairn
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Pacific::Pohnpei
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Pacific::Ponape
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Pacific::Rarotonga
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Pacific::Saipan
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Pacific::Samoa
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Pacific::Tahiti
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Pacific::Tarawa
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Pacific::Tongatapu
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Pacific::Truk
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Pacific::Wake
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Pacific::Wallis
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Pacific::Yap
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Poland
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Portugal
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::ROC
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::ROK
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Singapore
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Turkey
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::UCT
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::US
end
module TZInfo::Data::Definitions::US::Alaska
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::US::Aleutian
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::US::Arizona
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::US::Central
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::US::East__m__Indiana
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::US::Eastern
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::US::Hawaii
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::US::Indiana__m__Starke
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::US::Michigan
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::US::Mountain
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::US::Pacific
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::US::Samoa
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::UTC
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Universal
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::W__m__SU
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::WET
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
module TZInfo::Data::Definitions::Zulu
  extend TZInfo::TimezoneDefinition::ClassMethods
  include TZInfo::TimezoneDefinition
end
